import type { EnemyDef } from '../types'

/** The bestiary. HP/damage curves are tuned via tools/balance — see tests/balance.test.ts
 *  for the envelope the numbers must stay inside. */
const DEFS: EnemyDef[] = [
  // ── Zone 1: Hollowroot Cavern (lv 1–3) ──────────────────────────────
  {
    id: 'cave-golem',
    name: 'Cave Golem',
    intro: 'A Cave Golem lumbers out of the dark.',
    level: 1,
    rank: 'normal',
    hp: 80,
    swingTicks: 44,
    dmgMin: 4,
    dmgMax: 8,
    xp: 22,
    goldMin: 4,
    goldMax: 8,
    dropPct: 16,
    portrait: { family: 'golem', hue: 260 },
    mechanics: [],
  },
  {
    id: 'mossback-boar',
    name: 'Mossback Boar',
    intro: 'A Mossback Boar snorts and paws the stone.',
    level: 2,
    rank: 'normal',
    hp: 100,
    swingTicks: 34,
    dmgMin: 3,
    dmgMax: 6,
    xp: 30,
    goldMin: 5,
    goldMax: 10,
    dropPct: 16,
    portrait: { family: 'beast', hue: 140 },
    mechanics: [],
  },
  {
    id: 'gloomfang-spider',
    name: 'Gloomfang Spider',
    intro: 'A Gloomfang Spider drops silently from the ceiling.',
    level: 3,
    rank: 'normal',
    hp: 115,
    swingTicks: 46,
    dmgMin: 4,
    dmgMax: 8,
    xp: 38,
    goldMin: 6,
    goldMax: 11,
    dropPct: 18,
    portrait: { family: 'spider', hue: 300 },
    mechanics: [
      { kind: 'venom', name: 'Gloomfang Venom', everyTicks: 280, tickDamage: 2, intervalTicks: 20, tickCount: 5 },
    ],
  },
  {
    id: 'rockmaw-bruiser',
    name: 'Rockmaw Bruiser',
    intro: 'The ground shakes — a Rockmaw Bruiser wants your bones.',
    level: 3,
    rank: 'elite',
    hp: 240,
    swingTicks: 50,
    dmgMin: 7,
    dmgMax: 11,
    xp: 95,
    goldMin: 15,
    goldMax: 26,
    dropPct: 50,
    portrait: { family: 'golem', hue: 60 },
    mechanics: [{ kind: 'enrage', hpPct: 30, swingMult: 0.65, dmgMult: 1.4 }],
  },
  {
    id: 'grubthar',
    name: 'Grubthar, the Cave King',
    intro: 'GRUBTHAR, THE CAVE KING, heaves his bulk from the throne of rubble.',
    level: 4,
    rank: 'boss',
    hp: 440,
    swingTicks: 46,
    dmgMin: 8,
    dmgMax: 13,
    xp: 220,
    goldMin: 45,
    goldMax: 70,
    dropPct: 100,
    portrait: { family: 'golem', hue: 20 },
    mechanics: [{ kind: 'enrage', hpPct: 35, swingMult: 0.6, dmgMult: 1.45 }],
  },

  // ── Zone 2: Duskmire Weald (lv 4–6) ─────────────────────────────────
  {
    id: 'duskwolf',
    name: 'Duskwolf',
    intro: 'A Duskwolf slinks between the black trunks.',
    level: 4,
    rank: 'normal',
    hp: 160,
    swingTicks: 34,
    dmgMin: 6,
    dmgMax: 10,
    xp: 46,
    goldMin: 8,
    goldMax: 13,
    dropPct: 16,
    portrait: { family: 'beast', hue: 280 },
    mechanics: [],
  },
  {
    id: 'bog-lurker',
    name: 'Bog Lurker',
    intro: 'The mire heaves — a Bog Lurker rises, dripping.',
    level: 5,
    rank: 'normal',
    hp: 200,
    swingTicks: 48,
    dmgMin: 9,
    dmgMax: 14,
    xp: 54,
    goldMin: 9,
    goldMax: 15,
    dropPct: 16,
    portrait: { family: 'revenant', hue: 150 },
    mechanics: [],
  },
  {
    id: 'witchlight-wisp',
    name: 'Witchlight Wisp',
    intro: 'A Witchlight Wisp flickers hungrily toward you.',
    level: 5,
    rank: 'normal',
    hp: 150,
    swingTicks: 52,
    dmgMin: 5,
    dmgMax: 8,
    xp: 54,
    goldMin: 9,
    goldMax: 15,
    dropPct: 18,
    portrait: { family: 'wisp', hue: 195 },
    mechanics: [
      { kind: 'hardcast', name: 'Witchbolt', castTicks: 70, cooldownTicks: 260, dmgMin: 16, dmgMax: 24 },
    ],
  },
  {
    id: 'mirefiend-brute',
    name: 'Mirefiend Brute',
    intro: 'A Mirefiend Brute crashes through the reeds, roaring.',
    level: 6,
    rank: 'elite',
    hp: 400,
    swingTicks: 44,
    dmgMin: 11,
    dmgMax: 17,
    xp: 155,
    goldMin: 24,
    goldMax: 38,
    dropPct: 50,
    portrait: { family: 'titan', hue: 130 },
    mechanics: [{ kind: 'enrage', hpPct: 30, swingMult: 0.65, dmgMult: 1.4 }],
  },
  {
    id: 'bramble-widow',
    name: 'The Bramble Widow',
    intro: 'THE BRAMBLE WIDOW descends on a thread of thorns.',
    level: 7,
    rank: 'boss',
    hp: 850,
    swingTicks: 44,
    dmgMin: 12,
    dmgMax: 17,
    xp: 420,
    goldMin: 80,
    goldMax: 120,
    dropPct: 100,
    portrait: { family: 'spider', hue: 330 },
    mechanics: [
      { kind: 'venom', name: 'Widow Toxin', everyTicks: 240, tickDamage: 5, intervalTicks: 20, tickCount: 5 },
      { kind: 'hardcast', name: 'Toxic Burst', castTicks: 60, cooldownTicks: 320, dmgMin: 22, dmgMax: 32 },
    ],
  },

  // ── Zone 3: Stormcrag Peaks (lv 7–9) ────────────────────────────────
  {
    id: 'harpy-skyrender',
    name: 'Harpy Skyrender',
    intro: 'A Harpy Skyrender shrieks down from the crags.',
    level: 7,
    rank: 'normal',
    hp: 280,
    swingTicks: 32,
    dmgMin: 8,
    dmgMax: 13,
    xp: 70,
    goldMin: 12,
    goldMax: 19,
    dropPct: 16,
    portrait: { family: 'beast', hue: 220 },
    mechanics: [],
  },
  {
    id: 'stone-colossus',
    name: 'Stone Colossus',
    intro: 'A Stone Colossus unfolds from the mountainside.',
    level: 8,
    rank: 'normal',
    hp: 390,
    swingTicks: 56,
    dmgMin: 16,
    dmgMax: 24,
    xp: 78,
    goldMin: 13,
    goldMax: 21,
    dropPct: 16,
    portrait: { family: 'titan', hue: 250 },
    mechanics: [],
  },
  {
    id: 'frostmane-drake',
    name: 'Frostmane Drake',
    intro: 'A Frostmane Drake circles once, then lands hard.',
    level: 8,
    rank: 'normal',
    hp: 320,
    swingTicks: 44,
    dmgMin: 10,
    dmgMax: 15,
    xp: 78,
    goldMin: 13,
    goldMax: 21,
    dropPct: 18,
    portrait: { family: 'drake', hue: 210 },
    mechanics: [
      { kind: 'hardcast', name: 'Frostbreath', castTicks: 56, cooldownTicks: 260, dmgMin: 20, dmgMax: 28 },
    ],
  },
  {
    id: 'crag-behemoth',
    name: 'Crag Behemoth',
    intro: 'A Crag Behemoth bellows, splitting the thin air.',
    level: 9,
    rank: 'elite',
    hp: 680,
    swingTicks: 48,
    dmgMin: 14,
    dmgMax: 21,
    xp: 230,
    goldMin: 34,
    goldMax: 52,
    dropPct: 50,
    portrait: { family: 'titan', hue: 40 },
    mechanics: [{ kind: 'enrage', hpPct: 30, swingMult: 0.65, dmgMult: 1.4 }],
  },
  {
    id: 'kraghorn',
    name: 'Kraghorn, Thane of Storms',
    intro: 'KRAGHORN, THANE OF STORMS, steps out of the lightning.',
    level: 10,
    rank: 'boss',
    hp: 1400,
    swingTicks: 42,
    dmgMin: 16,
    dmgMax: 23,
    xp: 700,
    goldMin: 130,
    goldMax: 190,
    dropPct: 100,
    portrait: { family: 'titan', hue: 265 },
    mechanics: [
      { kind: 'hardcast', name: 'Thunderlance', castTicks: 64, cooldownTicks: 300, dmgMin: 30, dmgMax: 42 },
      { kind: 'enrage', hpPct: 25, swingMult: 0.7, dmgMult: 1.35 },
    ],
  },

  // ── Zone 4: The Ashen Wastes (lv 10–12) ─────────────────────────────
  {
    id: 'cinderhound',
    name: 'Cinderhound',
    intro: 'A Cinderhound pads closer, embers dripping from its jaw.',
    level: 10,
    rank: 'normal',
    hp: 430,
    swingTicks: 34,
    dmgMin: 10,
    dmgMax: 15,
    xp: 94,
    goldMin: 16,
    goldMax: 25,
    dropPct: 16,
    portrait: { family: 'beast', hue: 40 },
    mechanics: [],
  },
  {
    id: 'ash-revenant',
    name: 'Ash Revenant',
    intro: 'An Ash Revenant coalesces from the grey wind.',
    level: 11,
    rank: 'normal',
    hp: 480,
    swingTicks: 46,
    dmgMin: 13,
    dmgMax: 18,
    xp: 102,
    goldMin: 17,
    goldMax: 27,
    dropPct: 18,
    portrait: { family: 'revenant', hue: 20 },
    mechanics: [
      { kind: 'venom', name: 'Soulburn', everyTicks: 260, tickDamage: 6, intervalTicks: 20, tickCount: 5 },
    ],
  },
  {
    id: 'obsidian-behemoth',
    name: 'Obsidian Behemoth',
    intro: 'An Obsidian Behemoth grinds forward on legs of black glass.',
    level: 12,
    rank: 'normal',
    hp: 590,
    swingTicks: 58,
    dmgMin: 19,
    dmgMax: 27,
    xp: 110,
    goldMin: 18,
    goldMax: 29,
    dropPct: 16,
    portrait: { family: 'golem', hue: 310 },
    mechanics: [],
  },
  {
    id: 'pyroclast-titan',
    name: 'Pyroclast Titan',
    intro: 'A Pyroclast Titan erupts from the cinder field.',
    level: 12,
    rank: 'elite',
    hp: 1050,
    swingTicks: 50,
    dmgMin: 18,
    dmgMax: 25,
    xp: 330,
    goldMin: 48,
    goldMax: 72,
    dropPct: 50,
    portrait: { family: 'titan', hue: 30 },
    mechanics: [{ kind: 'enrage', hpPct: 30, swingMult: 0.65, dmgMult: 1.4 }],
  },
  {
    id: 'ashmaw',
    name: 'Pyrelord Ashmaw',
    intro: 'PYRELORD ASHMAW rises, and the wastes catch fire.',
    level: 13,
    rank: 'boss',
    hp: 2000,
    swingTicks: 44,
    dmgMin: 19,
    dmgMax: 26,
    xp: 1100,
    goldMin: 200,
    goldMax: 280,
    dropPct: 100,
    portrait: { family: 'drake', hue: 35 },
    mechanics: [
      { kind: 'enrage', hpPct: 30, swingMult: 0.7, dmgMult: 1.35 },
      { kind: 'hardcast', name: 'Cinder Nova', castTicks: 70, cooldownTicks: 340, dmgMin: 36, dmgMax: 48 },
    ],
  },

  // ── Zone 5: The Sundered Spire (lv 13–15) ───────────────────────────
  {
    id: 'void-acolyte',
    name: 'Void Acolyte',
    intro: 'A Void Acolyte turns toward you, chanting backwards.',
    level: 13,
    rank: 'normal',
    hp: 520,
    swingTicks: 48,
    dmgMin: 14,
    dmgMax: 19,
    xp: 118,
    goldMin: 20,
    goldMax: 31,
    dropPct: 18,
    portrait: { family: 'void', hue: 300 },
    mechanics: [
      { kind: 'hardcast', name: 'Void Bolt', castTicks: 60, cooldownTicks: 240, dmgMin: 24, dmgMax: 32 },
    ],
  },
  {
    id: 'bone-sentinel',
    name: 'Bone Sentinel',
    intro: 'A Bone Sentinel rattles to attention at the gate.',
    level: 14,
    rank: 'normal',
    hp: 600,
    swingTicks: 52,
    dmgMin: 20,
    dmgMax: 27,
    xp: 126,
    goldMin: 21,
    goldMax: 33,
    dropPct: 16,
    portrait: { family: 'revenant', hue: 260 },
    mechanics: [],
  },
  {
    id: 'riftspawn-horror',
    name: 'Riftspawn Horror',
    intro: 'A Riftspawn Horror folds itself into this world.',
    level: 14,
    rank: 'normal',
    hp: 600,
    swingTicks: 40,
    dmgMin: 16,
    dmgMax: 22,
    xp: 126,
    goldMin: 21,
    goldMax: 33,
    dropPct: 18,
    portrait: { family: 'void', hue: 330 },
    mechanics: [
      { kind: 'venom', name: 'Rift Rot', everyTicks: 240, tickDamage: 6, intervalTicks: 20, tickCount: 5 },
    ],
  },
  {
    id: 'herald-of-malgrath',
    name: 'Herald of Malgrath',
    intro: 'The Herald of Malgrath announces your death in three tongues.',
    level: 15,
    rank: 'elite',
    hp: 1250,
    swingTicks: 46,
    dmgMin: 21,
    dmgMax: 29,
    xp: 420,
    goldMin: 65,
    goldMax: 95,
    dropPct: 50,
    portrait: { family: 'void', hue: 280 },
    mechanics: [{ kind: 'enrage', hpPct: 30, swingMult: 0.65, dmgMult: 1.4 }],
  },
  {
    id: 'malgrath',
    name: 'Malgrath the Worldrender',
    intro: 'MALGRATH THE WORLDRENDER regards you the way a storm regards a candle.',
    level: 16,
    rank: 'boss',
    hp: 3100,
    swingTicks: 44,
    dmgMin: 22,
    dmgMax: 30,
    xp: 2400,
    goldMin: 400,
    goldMax: 550,
    dropPct: 100,
    portrait: { family: 'void', hue: 310 },
    mechanics: [
      { kind: 'enrage', hpPct: 30, swingMult: 0.7, dmgMult: 1.4 },
      { kind: 'hardcast', name: 'Worldrender', castTicks: 80, cooldownTicks: 360, dmgMin: 46, dmgMax: 62 },
      { kind: 'venom', name: 'Doomsong', everyTicks: 300, tickDamage: 7, intervalTicks: 20, tickCount: 6 },
    ],
  },
]

export const ENEMIES: Record<string, EnemyDef> = Object.fromEntries(DEFS.map((d) => [d.id, d]))
